fields:
    site_name2:
        label: Site name2
        comment: The website name as it should appear on the front-end
        default: Boosteur 2.0

    gc7_flashy:
        label: GC7 Flashy
        type: colorpicker
        assetVar: 'gc7flashy'
