en:
    ok: 'yes2'
fr:
    'GC7&apos;s tests for dynamical translations': 'Tests de GC7 pour traductions dynamiques'
    'Please select your language': 'S&apos;il vous plait, sélectionnez votre langue:'
    'Translation': "Traduction"
    "Hey, hello... How do you do ?": "Comment allez-vous ?"
    ok: 'oui2'
    'Guests': 'Invités2'
